version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: easyrun  
      MYSQL_DATABASE: easyrun      
      MYSQL_USER: easyrun                   
      MYSQL_PASSWORD: easyrun    
    ports:
      - "3306:3306"                      
    volumes:
      - mysql-data:/var/lib/mysql      
    networks:
      - my_network

volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge